server:
  port: 8080
spring:
  application:
    name: GatewayServer
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        enabled: true
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      #          lower-case-service-id: true
      routes:
        - id: resourceserver_1
          uri: lb://RESOURCESERVERA
          predicates:
            - Path=/resource/**
          filters:
            - StripPrefix=1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defualtZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    restart:
      enabled: true
    gateway:
      enabled: true