server:
  port: 8861
spring:
  profiles:
    active: native
  application:
    name: AdminServer
  devtools:
    add-properties: false
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
logging:
  level:
    root: error
    com.cn: debug