server:
  port: 8761
spring:
  application:
    name: EurekaServer
  profiles:
    active: native
  devtools:
    add-properties: false
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729
  boot:
    admin:
      client:
        enabled: true
  main:
    allow-bean-definition-overriding: true
eureka:
  server:
    peer-node-read-timeout-ms: 1000
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
logging:
  level:
    root: error
    com.cn: debug