server:
  port: 8900
spring:
  application:
    name: SecurityServer
  profiles:
    active: native
  boot:
    admin:
      client:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/mysql_security_try?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  devtools:
    additional-paths: src/main/java
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
logging:
  level:
    root: error
    com.cn: debug
jwt:
  signingKey: 123456