server:
  port: 8900
spring:
  application:
    name: SecurityServer
  profiles:
    active: native
  boot:
    admin:
      client:
        enabled: true
  devtools:
    add-properties: false
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: abcd
      password: abcd
      roles: admin
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS256
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
logging:
  level:
    root: error
    com.cn: debug