server:
  port: 8900
spring:
  application:
    name: SecurityServer
  profiles:
    active: native
  boot:
    admin:
      client:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/mysql_security_try?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    root: error
    com.cn: debug
jwt:
  signingKey: 123456