server:
  port: 8888
spring:
  boot:
    admin:
      client:
        enabled: true
  application:
    name: ConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  #        git:
  #          uri: https://github.com/linpeng109/sc_20181217/tree/master/configServer/src/main/resources
  #          username: linpeng109
  #          password: patient681020
  #          search-paths: /shared
  #          default-label: master
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    root: error
    com.cn: debug