server:
  port: 8888
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        # github
        git:
          uri: https://github.com/linpeng109/config-repo
        # local
  #        native:
  #          search-locations: classpath:/shared
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
  boot:
    admin:
      client:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    root: error
    com.cn: debug
