server:
  port: 8888
spring:
  boot:
    admin:
      client:
        enabled: true
  application:
    name: ConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        # github
        git:
          uri: http://github.com/linpeng109/config-repo
          username: linpeng109
          password: patient681020
          skip-ssl-validation: true
        # local
#        native:
  #          search-locations: classpath:/shared
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  server:
    servlet:
      context-path: /admin
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    root: error
    com.cn: debug