server:
  port: 8085
spring:
  application:
    name: ResourceServer_2
  boot:
    admin:
      client:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    root: error
    com.cn: debug
jwt:
  signingKey: 123456